// Generated by gencpp from file graspit_interface/FindInitialContactRequest.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_FINDINITIALCONTACTREQUEST_H
#define GRASPIT_INTERFACE_MESSAGE_FINDINITIALCONTACTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct FindInitialContactRequest_
{
  typedef FindInitialContactRequest_<ContainerAllocator> Type;

  FindInitialContactRequest_()
    : id(0)
    , moveDist(0.0)  {
    }
  FindInitialContactRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , moveDist(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef double _moveDist_type;
  _moveDist_type moveDist;





  typedef boost::shared_ptr< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindInitialContactRequest_

typedef ::graspit_interface::FindInitialContactRequest_<std::allocator<void> > FindInitialContactRequest;

typedef boost::shared_ptr< ::graspit_interface::FindInitialContactRequest > FindInitialContactRequestPtr;
typedef boost::shared_ptr< ::graspit_interface::FindInitialContactRequest const> FindInitialContactRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator1> & lhs, const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.moveDist == rhs.moveDist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator1> & lhs, const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbd1778788d31c656988ba49365c942d";
  }

  static const char* value(const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbd1778788d31c65ULL;
  static const uint64_t static_value2 = 0x6988ba49365c942dULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/FindInitialContactRequest";
  }

  static const char* value(const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"float64 moveDist\n"
"\n"
;
  }

  static const char* value(const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.moveDist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindInitialContactRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::FindInitialContactRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::FindInitialContactRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "moveDist: ";
    Printer<double>::stream(s, indent + "  ", v.moveDist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_FINDINITIALCONTACTREQUEST_H
