// Generated by gencpp from file graspit_interface/GetGraspableBodyRequest.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_GETGRASPABLEBODYREQUEST_H
#define GRASPIT_INTERFACE_MESSAGE_GETGRASPABLEBODYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct GetGraspableBodyRequest_
{
  typedef GetGraspableBodyRequest_<ContainerAllocator> Type;

  GetGraspableBodyRequest_()
    : id(0)  {
    }
  GetGraspableBodyRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGraspableBodyRequest_

typedef ::graspit_interface::GetGraspableBodyRequest_<std::allocator<void> > GetGraspableBodyRequest;

typedef boost::shared_ptr< ::graspit_interface::GetGraspableBodyRequest > GetGraspableBodyRequestPtr;
typedef boost::shared_ptr< ::graspit_interface::GetGraspableBodyRequest const> GetGraspableBodyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator1> & lhs, const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator1> & lhs, const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/GetGraspableBodyRequest";
  }

  static const char* value(const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
;
  }

  static const char* value(const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGraspableBodyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::GetGraspableBodyRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_GETGRASPABLEBODYREQUEST_H
