// Generated by gencpp from file graspit_interface/GetRobotResponse.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_GETROBOTRESPONSE_H
#define GRASPIT_INTERFACE_MESSAGE_GETROBOTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <graspit_interface/Robot.h>

namespace graspit_interface
{
template <class ContainerAllocator>
struct GetRobotResponse_
{
  typedef GetRobotResponse_<ContainerAllocator> Type;

  GetRobotResponse_()
    : robot()
    , result(0)  {
    }
  GetRobotResponse_(const ContainerAllocator& _alloc)
    : robot(_alloc)
    , result(0)  {
  (void)_alloc;
    }



   typedef  ::graspit_interface::Robot_<ContainerAllocator>  _robot_type;
  _robot_type robot;

   typedef uint8_t _result_type;
  _result_type result;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RESULT_SUCCESS)
  #undef RESULT_SUCCESS
#endif
#if defined(_WIN32) && defined(RESULT_INVALID_ID)
  #undef RESULT_INVALID_ID
#endif

  enum {
    RESULT_SUCCESS = 0u,
    RESULT_INVALID_ID = 1u,
  };


  typedef boost::shared_ptr< ::graspit_interface::GetRobotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::GetRobotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRobotResponse_

typedef ::graspit_interface::GetRobotResponse_<std::allocator<void> > GetRobotResponse;

typedef boost::shared_ptr< ::graspit_interface::GetRobotResponse > GetRobotResponsePtr;
typedef boost::shared_ptr< ::graspit_interface::GetRobotResponse const> GetRobotResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::GetRobotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::GetRobotResponse_<ContainerAllocator1> & lhs, const ::graspit_interface::GetRobotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.robot == rhs.robot &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::GetRobotResponse_<ContainerAllocator1> & lhs, const ::graspit_interface::GetRobotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::GetRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::GetRobotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::GetRobotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dab36ff1204e1f7f398f26f76b4ec4d7";
  }

  static const char* value(const ::graspit_interface::GetRobotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdab36ff1204e1f7fULL;
  static const uint64_t static_value2 = 0x398f26f76b4ec4d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/GetRobotResponse";
  }

  static const char* value(const ::graspit_interface::GetRobotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Robot robot\n"
"\n"
"uint8 RESULT_SUCCESS    = 0\n"
"uint8 RESULT_INVALID_ID = 1\n"
" \n"
"uint8 result\n"
"\n"
"\n"
"================================================================================\n"
"MSG: graspit_interface/Robot\n"
"std_msgs/Header header\n"
"\n"
"geometry_msgs/Pose pose\n"
"sensor_msgs/JointState[] joints\n"
"float64[] dofs\n"
"graspit_interface/TactileSensorData tactile\n"
"Contact[] contacts\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: graspit_interface/TactileSensorData\n"
"std_msgs/Header header\n"
"geometry_msgs/PoseStamped[] sensor_poses\n"
"float64[] sensor_forces\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: graspit_interface/Contact\n"
"string body1\n"
"string body2\n"
"\n"
"geometry_msgs/PoseStamped ps # in the graspit world frame\n"
"\n"
"float64 cof # coefficient of friction.\n"
"\n"
"\n"
;
  }

  static const char* value(const ::graspit_interface::GetRobotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRobotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::GetRobotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::GetRobotResponse_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    s << std::endl;
    Printer< ::graspit_interface::Robot_<ContainerAllocator> >::stream(s, indent + "  ", v.robot);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_GETROBOTRESPONSE_H
