// Generated by gencpp from file graspit_interface/PlanGraspsGoal.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_PLANGRASPSGOAL_H
#define GRASPIT_INTERFACE_MESSAGE_PLANGRASPSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <graspit_interface/Planner.h>
#include <graspit_interface/SearchSpace.h>
#include <graspit_interface/SearchContact.h>
#include <graspit_interface/SimAnnParams.h>

namespace graspit_interface
{
template <class ContainerAllocator>
struct PlanGraspsGoal_
{
  typedef PlanGraspsGoal_<ContainerAllocator> Type;

  PlanGraspsGoal_()
    : graspable_body_id(0)
    , planner()
    , search_energy()
    , search_space()
    , search_contact()
    , sim_ann_params()
    , max_steps(0)
    , feedback_num_steps(0)  {
    }
  PlanGraspsGoal_(const ContainerAllocator& _alloc)
    : graspable_body_id(0)
    , planner(_alloc)
    , search_energy(_alloc)
    , search_space(_alloc)
    , search_contact(_alloc)
    , sim_ann_params(_alloc)
    , max_steps(0)
    , feedback_num_steps(0)  {
  (void)_alloc;
    }



   typedef int32_t _graspable_body_id_type;
  _graspable_body_id_type graspable_body_id;

   typedef  ::graspit_interface::Planner_<ContainerAllocator>  _planner_type;
  _planner_type planner;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _search_energy_type;
  _search_energy_type search_energy;

   typedef  ::graspit_interface::SearchSpace_<ContainerAllocator>  _search_space_type;
  _search_space_type search_space;

   typedef  ::graspit_interface::SearchContact_<ContainerAllocator>  _search_contact_type;
  _search_contact_type search_contact;

   typedef  ::graspit_interface::SimAnnParams_<ContainerAllocator>  _sim_ann_params_type;
  _sim_ann_params_type sim_ann_params;

   typedef int32_t _max_steps_type;
  _max_steps_type max_steps;

   typedef int32_t _feedback_num_steps_type;
  _feedback_num_steps_type feedback_num_steps;





  typedef boost::shared_ptr< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PlanGraspsGoal_

typedef ::graspit_interface::PlanGraspsGoal_<std::allocator<void> > PlanGraspsGoal;

typedef boost::shared_ptr< ::graspit_interface::PlanGraspsGoal > PlanGraspsGoalPtr;
typedef boost::shared_ptr< ::graspit_interface::PlanGraspsGoal const> PlanGraspsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator1> & lhs, const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.graspable_body_id == rhs.graspable_body_id &&
    lhs.planner == rhs.planner &&
    lhs.search_energy == rhs.search_energy &&
    lhs.search_space == rhs.search_space &&
    lhs.search_contact == rhs.search_contact &&
    lhs.sim_ann_params == rhs.sim_ann_params &&
    lhs.max_steps == rhs.max_steps &&
    lhs.feedback_num_steps == rhs.feedback_num_steps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator1> & lhs, const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18f1b3ccd1d8b357cb312d3a46fdb7ac";
  }

  static const char* value(const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18f1b3ccd1d8b357ULL;
  static const uint64_t static_value2 = 0xcb312d3a46fdb7acULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/PlanGraspsGoal";
  }

  static const char* value(const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"int32 graspable_body_id\n"
"\n"
"Planner planner\n"
"string search_energy\n"
"SearchSpace search_space\n"
"SearchContact search_contact\n"
"SimAnnParams sim_ann_params\n"
"\n"
"int32 max_steps\n"
"int32 feedback_num_steps\n"
"\n"
"================================================================================\n"
"MSG: graspit_interface/Planner\n"
"uint8 SIM_ANN                      = 0\n"
"uint8 MULTI_THREADED               = 1\n"
"\n"
"uint8 type\n"
"================================================================================\n"
"MSG: graspit_interface/SearchSpace\n"
"uint8 SPACE_AXIS_ANGLE    = 0\n"
"uint8 SPACE_COMPLETE      = 1\n"
"uint8 SPACE_ELLIPSOID     = 2\n"
"uint8 SPACE_APPROACH      = 3\n"
"\n"
"uint8 type\n"
"================================================================================\n"
"MSG: graspit_interface/SearchContact\n"
"uint8 CONTACT_PRESET    = 0\n"
"uint8 CONTACT_LIVE      = 1\n"
"\n"
"uint8 type	\n"
"================================================================================\n"
"MSG: graspit_interface/SimAnnParams\n"
"\n"
"# flag to switch to custom params defined in this message. If not set, GraspIt's default settings are kept\n"
"bool set_custom_params\n"
"\n"
"\n"
"# //Annealing parameters\n"
"# //! Annealing constant for neighbor generation schedule\n"
"float64 YC	 	#	GraspIt! default: 7.0\n"
"# //! Annealing constant for error acceptance schedule\n"
"float64 HC	 	#	GraspIt! default: 7.0\n"
"# //! Number of dimensions for neighbor generation schedule\n"
"float64 YDIMS	#	GraspIt! default: 8.0\n"
"# //! Number of dimensions for error acceptance schedule\n"
"float64 HDIMS	#	GraspIt! default: 8.0\n"
"# //! Adjust factor for neighbor generation schedule\n"
"float64 NBR_ADJ	#	GraspIt! default: 1.0\n"
"# //! Adjust raw errors reported by states to be in the relevant range of the annealing schedule\n"
"float64 ERR_ADJ	#	GraspIt! default: 1.0e-6\n"
"# //! Starting temperatue\n"
"float64 DEF_T0	#	GraspIt! default: 1e6\n"
"# //! Starting step\n"
"float64 DEF_K0	#	GraspIt! default: 30000\n"
;
  }

  static const char* value(const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.graspable_body_id);
      stream.next(m.planner);
      stream.next(m.search_energy);
      stream.next(m.search_space);
      stream.next(m.search_contact);
      stream.next(m.sim_ann_params);
      stream.next(m.max_steps);
      stream.next(m.feedback_num_steps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanGraspsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::PlanGraspsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::PlanGraspsGoal_<ContainerAllocator>& v)
  {
    s << indent << "graspable_body_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.graspable_body_id);
    s << indent << "planner: ";
    s << std::endl;
    Printer< ::graspit_interface::Planner_<ContainerAllocator> >::stream(s, indent + "  ", v.planner);
    s << indent << "search_energy: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.search_energy);
    s << indent << "search_space: ";
    s << std::endl;
    Printer< ::graspit_interface::SearchSpace_<ContainerAllocator> >::stream(s, indent + "  ", v.search_space);
    s << indent << "search_contact: ";
    s << std::endl;
    Printer< ::graspit_interface::SearchContact_<ContainerAllocator> >::stream(s, indent + "  ", v.search_contact);
    s << indent << "sim_ann_params: ";
    s << std::endl;
    Printer< ::graspit_interface::SimAnnParams_<ContainerAllocator> >::stream(s, indent + "  ", v.sim_ann_params);
    s << indent << "max_steps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.max_steps);
    s << indent << "feedback_num_steps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback_num_steps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_PLANGRASPSGOAL_H
