// Generated by gencpp from file graspit_interface/SetRobotPoseResponse.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_SETROBOTPOSERESPONSE_H
#define GRASPIT_INTERFACE_MESSAGE_SETROBOTPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct SetRobotPoseResponse_
{
  typedef SetRobotPoseResponse_<ContainerAllocator> Type;

  SetRobotPoseResponse_()
    : result(0)  {
    }
  SetRobotPoseResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RESULT_SUCCESS)
  #undef RESULT_SUCCESS
#endif
#if defined(_WIN32) && defined(RESULT_INVALID_ID)
  #undef RESULT_INVALID_ID
#endif
#if defined(_WIN32) && defined(RESULT_INVALID_POSE)
  #undef RESULT_INVALID_POSE
#endif
#if defined(_WIN32) && defined(RESULT_ROBOT_IN_COLLISION)
  #undef RESULT_ROBOT_IN_COLLISION
#endif

  enum {
    RESULT_SUCCESS = 0u,
    RESULT_INVALID_ID = 1u,
    RESULT_INVALID_POSE = 2u,
    RESULT_ROBOT_IN_COLLISION = 3u,
  };


  typedef boost::shared_ptr< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotPoseResponse_

typedef ::graspit_interface::SetRobotPoseResponse_<std::allocator<void> > SetRobotPoseResponse;

typedef boost::shared_ptr< ::graspit_interface::SetRobotPoseResponse > SetRobotPoseResponsePtr;
typedef boost::shared_ptr< ::graspit_interface::SetRobotPoseResponse const> SetRobotPoseResponseConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator1> & lhs, const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator1> & lhs, const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b525b6eb173a26da257cb4c74fee269d";
  }

  static const char* value(const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb525b6eb173a26daULL;
  static const uint64_t static_value2 = 0x257cb4c74fee269dULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/SetRobotPoseResponse";
  }

  static const char* value(const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 RESULT_SUCCESS            = 0\n"
"uint8 RESULT_INVALID_ID         = 1\n"
"uint8 RESULT_INVALID_POSE       = 2\n"
"uint8 RESULT_ROBOT_IN_COLLISION = 3\n"
"\n"
"uint8 result\n"
"\n"
;
  }

  static const char* value(const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::SetRobotPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_SETROBOTPOSERESPONSE_H
