// Generated by gencpp from file graspit_interface/GetDynamicsResponse.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_GETDYNAMICSRESPONSE_H
#define GRASPIT_INTERFACE_MESSAGE_GETDYNAMICSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct GetDynamicsResponse_
{
  typedef GetDynamicsResponse_<ContainerAllocator> Type;

  GetDynamicsResponse_()
    : dynamicsEnabled(false)  {
    }
  GetDynamicsResponse_(const ContainerAllocator& _alloc)
    : dynamicsEnabled(false)  {
  (void)_alloc;
    }



   typedef uint8_t _dynamicsEnabled_type;
  _dynamicsEnabled_type dynamicsEnabled;





  typedef boost::shared_ptr< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDynamicsResponse_

typedef ::graspit_interface::GetDynamicsResponse_<std::allocator<void> > GetDynamicsResponse;

typedef boost::shared_ptr< ::graspit_interface::GetDynamicsResponse > GetDynamicsResponsePtr;
typedef boost::shared_ptr< ::graspit_interface::GetDynamicsResponse const> GetDynamicsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator1> & lhs, const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.dynamicsEnabled == rhs.dynamicsEnabled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator1> & lhs, const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6fee31102eceebe1746ef7051cbdb2f";
  }

  static const char* value(const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6fee31102eceebeULL;
  static const uint64_t static_value2 = 0x1746ef7051cbdb2fULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/GetDynamicsResponse";
  }

  static const char* value(const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool dynamicsEnabled\n"
"\n"
;
  }

  static const char* value(const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dynamicsEnabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDynamicsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::GetDynamicsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::GetDynamicsResponse_<ContainerAllocator>& v)
  {
    s << indent << "dynamicsEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dynamicsEnabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_GETDYNAMICSRESPONSE_H
