// Generated by gencpp from file graspit_interface/MoveDOFToContactsRequest.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_MOVEDOFTOCONTACTSREQUEST_H
#define GRASPIT_INTERFACE_MESSAGE_MOVEDOFTOCONTACTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct MoveDOFToContactsRequest_
{
  typedef MoveDOFToContactsRequest_<ContainerAllocator> Type;

  MoveDOFToContactsRequest_()
    : id(0)
    , dofs()
    , desired_steps()
    , stopAtContact(false)  {
    }
  MoveDOFToContactsRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , dofs(_alloc)
    , desired_steps(_alloc)
    , stopAtContact(false)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _dofs_type;
  _dofs_type dofs;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _desired_steps_type;
  _desired_steps_type desired_steps;

   typedef uint8_t _stopAtContact_type;
  _stopAtContact_type stopAtContact;





  typedef boost::shared_ptr< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveDOFToContactsRequest_

typedef ::graspit_interface::MoveDOFToContactsRequest_<std::allocator<void> > MoveDOFToContactsRequest;

typedef boost::shared_ptr< ::graspit_interface::MoveDOFToContactsRequest > MoveDOFToContactsRequestPtr;
typedef boost::shared_ptr< ::graspit_interface::MoveDOFToContactsRequest const> MoveDOFToContactsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator1> & lhs, const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.dofs == rhs.dofs &&
    lhs.desired_steps == rhs.desired_steps &&
    lhs.stopAtContact == rhs.stopAtContact;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator1> & lhs, const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90a2bae5e7d3766f6dd04069adf108c6";
  }

  static const char* value(const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90a2bae5e7d3766fULL;
  static const uint64_t static_value2 = 0x6dd04069adf108c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/MoveDOFToContactsRequest";
  }

  static const char* value(const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"float64[] dofs\n"
"float64[] desired_steps\n"
"bool stopAtContact\n"
"\n"
;
  }

  static const char* value(const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.dofs);
      stream.next(m.desired_steps);
      stream.next(m.stopAtContact);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveDOFToContactsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::MoveDOFToContactsRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "dofs[]" << std::endl;
    for (size_t i = 0; i < v.dofs.size(); ++i)
    {
      s << indent << "  dofs[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.dofs[i]);
    }
    s << indent << "desired_steps[]" << std::endl;
    for (size_t i = 0; i < v.desired_steps.size(); ++i)
    {
      s << indent << "  desired_steps[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.desired_steps[i]);
    }
    s << indent << "stopAtContact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stopAtContact);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_MOVEDOFTOCONTACTSREQUEST_H
