// Generated by gencpp from file graspit_interface/Planner.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_PLANNER_H
#define GRASPIT_INTERFACE_MESSAGE_PLANNER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct Planner_
{
  typedef Planner_<ContainerAllocator> Type;

  Planner_()
    : type(0)  {
    }
  Planner_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SIM_ANN)
  #undef SIM_ANN
#endif
#if defined(_WIN32) && defined(MULTI_THREADED)
  #undef MULTI_THREADED
#endif

  enum {
    SIM_ANN = 0u,
    MULTI_THREADED = 1u,
  };


  typedef boost::shared_ptr< ::graspit_interface::Planner_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::Planner_<ContainerAllocator> const> ConstPtr;

}; // struct Planner_

typedef ::graspit_interface::Planner_<std::allocator<void> > Planner;

typedef boost::shared_ptr< ::graspit_interface::Planner > PlannerPtr;
typedef boost::shared_ptr< ::graspit_interface::Planner const> PlannerConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::Planner_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::Planner_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::Planner_<ContainerAllocator1> & lhs, const ::graspit_interface::Planner_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::Planner_<ContainerAllocator1> & lhs, const ::graspit_interface::Planner_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::Planner_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::Planner_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::Planner_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::Planner_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::Planner_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::Planner_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::Planner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f72709c2fd658bcbafe72047dc86825";
  }

  static const char* value(const ::graspit_interface::Planner_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f72709c2fd658bcULL;
  static const uint64_t static_value2 = 0xbafe72047dc86825ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::Planner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/Planner";
  }

  static const char* value(const ::graspit_interface::Planner_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::Planner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 SIM_ANN                      = 0\n"
"uint8 MULTI_THREADED               = 1\n"
"\n"
"uint8 type\n"
;
  }

  static const char* value(const ::graspit_interface::Planner_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::Planner_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Planner_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::Planner_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::Planner_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_PLANNER_H
