// Generated by gencpp from file graspit_interface/TactileSensorData.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_TACTILESENSORDATA_H
#define GRASPIT_INTERFACE_MESSAGE_TACTILESENSORDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace graspit_interface
{
template <class ContainerAllocator>
struct TactileSensorData_
{
  typedef TactileSensorData_<ContainerAllocator> Type;

  TactileSensorData_()
    : header()
    , sensor_poses()
    , sensor_forces()  {
    }
  TactileSensorData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_poses(_alloc)
    , sensor_forces(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _sensor_poses_type;
  _sensor_poses_type sensor_poses;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _sensor_forces_type;
  _sensor_forces_type sensor_forces;





  typedef boost::shared_ptr< ::graspit_interface::TactileSensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::TactileSensorData_<ContainerAllocator> const> ConstPtr;

}; // struct TactileSensorData_

typedef ::graspit_interface::TactileSensorData_<std::allocator<void> > TactileSensorData;

typedef boost::shared_ptr< ::graspit_interface::TactileSensorData > TactileSensorDataPtr;
typedef boost::shared_ptr< ::graspit_interface::TactileSensorData const> TactileSensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::TactileSensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::TactileSensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graspit_interface::TactileSensorData_<ContainerAllocator1> & lhs, const ::graspit_interface::TactileSensorData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensor_poses == rhs.sensor_poses &&
    lhs.sensor_forces == rhs.sensor_forces;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graspit_interface::TactileSensorData_<ContainerAllocator1> & lhs, const ::graspit_interface::TactileSensorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::TactileSensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::TactileSensorData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::TactileSensorData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8b9e263562c22cdc89622a214c2dd89";
  }

  static const char* value(const ::graspit_interface::TactileSensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8b9e263562c22cdULL;
  static const uint64_t static_value2 = 0xc89622a214c2dd89ULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/TactileSensorData";
  }

  static const char* value(const ::graspit_interface::TactileSensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/PoseStamped[] sensor_poses\n"
"float64[] sensor_forces\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::graspit_interface::TactileSensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_poses);
      stream.next(m.sensor_forces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TactileSensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::TactileSensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graspit_interface::TactileSensorData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_poses[]" << std::endl;
    for (size_t i = 0; i < v.sensor_poses.size(); ++i)
    {
      s << indent << "  sensor_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.sensor_poses[i]);
    }
    s << indent << "sensor_forces[]" << std::endl;
    for (size_t i = 0; i < v.sensor_forces.size(); ++i)
    {
      s << indent << "  sensor_forces[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sensor_forces[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_TACTILESENSORDATA_H
