// Generated by gencpp from file graspit_interface/ToggleAllCollisionsResponse.msg
// DO NOT EDIT!


#ifndef GRASPIT_INTERFACE_MESSAGE_TOGGLEALLCOLLISIONSRESPONSE_H
#define GRASPIT_INTERFACE_MESSAGE_TOGGLEALLCOLLISIONSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graspit_interface
{
template <class ContainerAllocator>
struct ToggleAllCollisionsResponse_
{
  typedef ToggleAllCollisionsResponse_<ContainerAllocator> Type;

  ToggleAllCollisionsResponse_()
    {
    }
  ToggleAllCollisionsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleAllCollisionsResponse_

typedef ::graspit_interface::ToggleAllCollisionsResponse_<std::allocator<void> > ToggleAllCollisionsResponse;

typedef boost::shared_ptr< ::graspit_interface::ToggleAllCollisionsResponse > ToggleAllCollisionsResponsePtr;
typedef boost::shared_ptr< ::graspit_interface::ToggleAllCollisionsResponse const> ToggleAllCollisionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace graspit_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graspit_interface/ToggleAllCollisionsResponse";
  }

  static const char* value(const ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleAllCollisionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::graspit_interface::ToggleAllCollisionsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GRASPIT_INTERFACE_MESSAGE_TOGGLEALLCOLLISIONSRESPONSE_H
